### ISSUE TITLE
Non async trigger in browser

### ISSUE THREAD

**Issue by jaetask** [munkychop/bullet#4]
Hi,

It would be awesome to be able to not use setTimeout in the browser when running unit tests via a jasmine spec runner. Currently there is a detection in place, and setTimeout is forced. Would it be possible to add a config item, or conditional? 

``` javascript
// Check whether or not this is a browser environment.
if (typeof window !== 'undefined')
{
    window.setTimeout(runCallback, 0);
}
else
{
    runCallback();
}
```

Thanks

**Comment by munkychop** [comment]
@jaetask sure, that sounds useful. I'll add a method to toggle sync/async triggers.

**Comment by munkychop** [comment]
@jaetask this is implemented in [release 2.2.0](https://github.com/munkychop/bullet/releases/tag/2.2.0), which has also been published to npm :smile:
See the docs for more info.

**Comment by jaetask** [comment]
Hi, I have just finished testing this and can confirm it has worked like a charm! Many thanks

**Comment by munkychop** [comment]
@jaetask Glad to hear it :+1:
